### ISSUE TITLE
Problems with the new dribbble update

### ISSUE THREAD

**Issue by sdaverede** [Aerolab/booom#21]
Hi guys! First of all, thanks for develop this amazing extension!

Today I noticed a few problems with dribbble, that get fixed when I disable the extension, so the problem comes with the new update on the site that finally replaced the pagination for the infinite scroll, as the app used to do since a long time ago, but apparently, this seems to interfere now. Also I see a duplicated "scroll to top" button (because dribbble added it own button now).

Thanks in advance!

**Comment by btomino** [comment]
![screen shot 2015-07-17 at 9 11 46 am](https://cloud.githubusercontent.com/assets/8557648/8747785/e712ae2c-2c63-11e5-924c-c1ba6af3d4d6.png)

Hello guys, thank you so much for making my life and others easier when viewing dribbble with this wonderful extension! However with the new update, it seems that the shots disappear when scrolling a little down the page. I'm not sure if the infinite scroll with both are conflicting it.

Thank you!

**Comment by RobertoGonzalez** [comment]
We're working on it! There's a couple issues with auto @2x, but all other modules are now working in the feature/fixRedesign2 branch.

**Comment by RobertoGonzalez** [comment]
Check out this link in an hour or so to download the latest release (0.2.3). We left a few issues in there to fix the most important issues quickly. 
https://chrome.google.com/webstore/detail/booom-dribbble-enhancemen/ijjmibmmkoeglapejdlifckjcfalbopb
