### ISSUE TITLE
Only first 9 thumbnails load until reinstall

### ISSUE THREAD

**Issue by warpling** [Aerolab/booom#22]
Booom v0.2.2
Chrome  43.0.2357.134 (64-bit)
Mac OS 10.11 beta (15A216g)

Only the first 12 thumbnails were loading for me on any page with infinite scrolling, other information about the posts would load fine. Reinstalling seemed to fix the issue. Thought this issue may still be helpful to debug though. I apologize for not having thought to grab the console output before reinstalling.

![screen shot 2015-07-17 at 10 30 54 am](https://cloud.githubusercontent.com/assets/220240/8753249/f4810ca6-2c6e-11e5-8c7e-66b4f458ca0e.png)

**Comment by RobertoGonzalez** [comment]
@warpling That issue seemed to be caused by the previous redesign by Dribbble (which added infinite scrolling and a few features that conflicted with booom). The latest builds seem to work fine.

**Comment by warpling** [comment]
Awesome :) thanks for the fantastic extension!
