### ISSUE TITLE
Dribbble Updates Break Booom

### ISSUE THREAD

**Issue by asiahoe** [Aerolab/booom#23]
Dribbble recently launched some updates that change the way thumbnails flow on larger screens. Shots also now open in a modal. More information available on [this tweet](https://twitter.com/dribbble/status/624596018827431938) from today.

So far, the main breaking point is that thumbnails only show 2 x 2 with Booom enabled.

![screenshot 2015-07-24 16 55 29](https://cloud.githubusercontent.com/assets/5003835/8884475/ed648342-3224-11e5-81ea-88978b2f82e7.png)

**Comment by RobertoGonzalez** [comment]
Fixed and published!
