### ISSUE TITLE
Dribbble updated their UI again...

### ISSUE THREAD

**Issue by dotcommer** [Aerolab/booom#24]
Could you update booom so that it works better with the shots page?  Right now it shows two on a row, with a third one below that row, repeating.  Its acting like the browser window is as wide as a smartphone or tablet or something.

**Comment by RobertoGonzalez** [comment]
That should have been fixed a few days ago. Try reinstalling the plugin. Are you using Chrome or Safari?

**Comment by dotcommer** [comment]
I installed this extension yesterday so that can't be the issue.

Running chrome:  Version 43.0.2357.132 (64-bit)
Mac OSX 10.9.5

Just checked again, shots page doesn't display properly, but likes and
other pages do.

-Bryan

**Comment by hogash** [comment]
Hey @RobertoGonzalez here's a screenshot of the newest UI update that's overwriting the injected styles (margins) http://hogash.d.pr/19GBF .

PS: Love the extension, makes lives better! :+1:

**Comment by RobertoGonzalez** [comment]
@hogash I've uploaded (yet another) minor release, which should address that issue. You'll be able to [download it from the chrome web store](https://chrome.google.com/webstore/detail/ijjmibmmkoeglapejdlifckjcfalbopb) in the next hour or so. Thanks for the report!

**Comment by dotcommer** [comment]
New update works great!  My life is complete.  I can die happy browsing
dribble with three shots per row.  Thank you.

How do I throw money at you to show my appreciation?

-Bryan

**Comment by RobertoGonzalez** [comment]
@dotcommer Thanks for the comments! A good review is all we ask for :D
